### ISSUE TITLE
Initializing RtAudio with a specific API

### ISSUE THREAD

**Issue by sinosoidal** [thestk/rtaudio#112]
I have compiled RtAudio with all drivers support on Windows however I'm not finding possible to initialise RtAudio with a specific API on Windows. It seems that no matter which API parameter I pass to the constructor, it always initialises with ASIO driver. I can however change to other driver afterwards, which is even more strange. Does anyone has a clue of what might be happening?

**Comment by radarsat1** [comment]
It seems the code in `RtAudio::openRtApi` is not quite right, it always discards the first selection and only keeps the last one.  I'm surprised you say it always selects the ASIO driver, since that is listed first.  Anyways, it definitely looks like something not quite right there. Can you trace the function in a debugger and figure it out?

**Comment by sinosoidal** [comment]
After all, it was my mistake. I was not doing things properly.
