### ISSUE TITLE
ASIO SDK version

### ISSUE THREAD

**Issue by samuel-tranchet** [thestk/rtaudio#16]
Hello, I'm new to RtAudio world, i'm having a test on it for a real-time audio processing application on Mac and Windows.

I saw that version 2.1 of ASIO SDK comes with the library, current version from steinberg is 2.3, is there a special reason to use 2.1 ? It's just a question not a query, if it's just a matter of time, perhaps I could help when my knowledge is sufficient.

Thanks a lot for your work.

**Comment by garyscavone** [comment]
Never heard back ... anyone want to download the updated ASIO files and see if they can simply be "dropped in"?

**Comment by pkviet** [comment]
@garyscavone 

hi,
interested also in the update:

Changes in ASIO 2.2 since ASIO 2.1 - **added support for Windows 64 bit**

Changes in ASIO 2.3 since ASIO 2.2 - added host queries to detect the driver's buffering and drop-out detection capabilities - some additional documentation on MMCSS; see page 46 of 'ASIO SDK 2.3.pdf' - dropped support for Mac OS 8 and 9

I'll try to drop in  the files as you suggest and report back.

**Comment by pkviet** [comment]
Got no issue with just copy paste sdk 2.3 instead of 2.1.
Compiles fine; I am using the dll and lib for an app and no change from sdk 2.1 : all is working.

**Comment by garyscavone** [comment]
We have version 2.3 files now ... closing.
