### ISSUE TITLE
Latency starting channels with WASAPI

### ISSUE THREAD

**Issue by rick-spada** [thestk/rtaudio#209]
I've been experimenting with RtAudio in our products and I've noticed that there's a significant amount of latency (150ms) when starting an input channel.  Looking at the code, there seems to be an awful lot of work going on prior to getting into the read/play samples loop.  Is this latency a known issue with WASAPI?

**Comment by MarcusTomlinson** [comment]
There are a few things to consider in a situation like this: Is the hardware dictating the minimum buffer? Is WASAPI / Windows dictating it? Is your application setting a buffer that's too large? It's hard to determine exactly why you may be experiencing latency without more details about your use case of course.

Mose issues of latency revolve around the issues above, and it's because of them that a lot of work has to be done in ring buffers between WASAPI and the user. Of course it's possible that this buffering is not quite as optimal as it could be.

How does this latency compare to an output-only, or duplex stream?

**Comment by rick-spada** [comment]
Let me clarify the latency that I'm measuring.  I'm measuring the time between when I start an input stream and the input wave callback starts getting called.  In my case, that's about 150 ms and should be independent of buffer size.

I measured output stream startup latency and that's much lower, about 25 ms.  Unfortunately, my product doesn't use duplex channels, so I can't provide a measurement for that.

**Comment by rick-spada** [comment]
I did some more experiments and discovered that the startup latency is a function of buffer size.  The smaller the buffer, the shorter the startup latency.
