### ISSUE TITLE
getDefaultOutputDevice returns wrong index on Ubuntu ALSA

### ISSUE THREAD

**Issue by witaly-iwanow** [thestk/rtaudio#224]
I've modified playsaw sample a little to use ALSA instead of PulseAudio (PA works fine, but I need to switch audio devices which doesn't seem to be possible with PA+RtAudio), and it now it fails to detect the default output device (always takes 0, but it has to be the last one). Here's the log I get:
~/rtaudio/_cmake$ tests/playsaw 1 48000
num devices: 8
0 hw:HDA Intel HDMI,3
1 hw:HDA Intel HDMI,7
2 hw:HDA Intel HDMI,8
3 hw:HDA Intel HDMI,9
4 hw:HDA Intel HDMI,10
5 hw:HDA Intel PCH,0
6 hw:HDA Intel PCH,1
7 default
getDefaultOutputDevice returned 0

Playing ... press <enter> to quit (buffer size = 512).
RtAudio alsa: _NOT_ running realtime scheduling

<no sound>

"tests/playsaw 1 48000 7" works as expected
[playsaw.cpp.txt](https://github.com/thestk/rtaudio/files/3787030/playsaw.cpp.txt)

**Comment by witaly-iwanow** [comment]
I'm on MacBook Pro 2015 something with Ubuntu 19.10 installed (real thing, not VM)

**Comment by radarsat1** [comment]
I agree that there is a problem here, I was struggling with something similar yesterday.. I was getting errors opening the default device and found it was trying to open "hw:0" instead of "default", which didn't work because pulse audio was running.

I would like to look into it but don't have time at the moment unfortunately.  What should be the correct behaviour?  Should "default" be device 0?  When I do have time, I'll have to go back and re-read previous work on the alsa backend, because I remember this has been worked on before.

**Comment by radarsat1** [comment]
I just committed dd23b6598b8e7f74d098628c852188a0d81e3562 which moves "default" to device 0.

In doing so however I've noticed that the way we enumerate devices is not really correct, at least with respect to how the "aplay" utility works that comes with ALSA.

In aplay, you can list "devices" (option `-l`) or "pcms" (option `-L`).  Our method corresponds more with "devices", where we iterate over devices and subdevices.  However the loop iterating over "pcms" is much simpler and includes more meaningful names.  Also, the `-D` option used to select the play device corresponds with the "PCM", or this latter iteration loop, not the one we use:

```
$ man aplay | grep -A1 -- --device
       -D, --device=NAME
              Select PCM by name
```

Therefore I'll see if I can change how ALSA device iteration works so that you can select by PCM instead of "devices/subdevice".

**Comment by radarsat1** [comment]
Here's what my system gives for these two options of aplay:

```
$ aplay -l | grep card
card 0: PCH [HDA Intel PCH], device 0: Generic Analog [Generic Analog]
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
card 0: PCH [HDA Intel PCH], device 9: HDMI 3 [HDMI 3]
card 0: PCH [HDA Intel PCH], device 10: HDMI 4 [HDMI 4]

$ aplay -L | grep -v -e '^ '
default
null
pulse
sysdefault:CARD=PCH
front:CARD=PCH,DEV=0
surround21:CARD=PCH,DEV=0
surround40:CARD=PCH,DEV=0
surround41:CARD=PCH,DEV=0
surround50:CARD=PCH,DEV=0
surround51:CARD=PCH,DEV=0
surround71:CARD=PCH,DEV=0
hdmi:CARD=PCH,DEV=0
hdmi:CARD=PCH,DEV=1
hdmi:CARD=PCH,DEV=2
hdmi:CARD=PCH,DEV=3
hdmi:CARD=PCH,DEV=4
dmix:CARD=PCH,DEV=0
dmix:CARD=PCH,DEV=3
dmix:CARD=PCH,DEV=7
dmix:CARD=PCH,DEV=8
dmix:CARD=PCH,DEV=9
dmix:CARD=PCH,DEV=10
dsnoop:CARD=PCH,DEV=0
dsnoop:CARD=PCH,DEV=3
dsnoop:CARD=PCH,DEV=7
dsnoop:CARD=PCH,DEV=8
dsnoop:CARD=PCH,DEV=9
dsnoop:CARD=PCH,DEV=10
hw:CARD=PCH,DEV=0
hw:CARD=PCH,DEV=3
hw:CARD=PCH,DEV=7
hw:CARD=PCH,DEV=8
hw:CARD=PCH,DEV=9
hw:CARD=PCH,DEV=10
plughw:CARD=PCH,DEV=0
plughw:CARD=PCH,DEV=3
plughw:CARD=PCH,DEV=7
plughw:CARD=PCH,DEV=8
plughw:CARD=PCH,DEV=9
plughw:CARD=PCH,DEV=10
```

The code for `device_list` and `pcm_list` can be [found here[(https://git.alsa-project.org/?p=alsa-utils.git;a=blob;f=aplay/aplay.c).

Now, neither of these seems _particularly_ appetizing to me for device enumeration.  If I look at what gets display e.g. by Audacity on my system, I get a nice short and reasonable list:

![image](https://user-images.githubusercontent.com/66805/78775324-549f4200-7996-11ea-8654-4b714a2c10ef.png)

So I'll have a look in there to see how that list gets generated.

**Comment by sthurian** [comment]
Audacity uses PortAudio under the hood. [This](https://github.com/audacity/portaudio/blob/master/src/hostapi/alsa/pa_linux_alsa.c#L1227) is how they do it. Not sure if this list is filtered on a higher application level by audacity

**Comment by garyscavone** [comment]
I'm closing this as there were various updates to the ALSA device querying code in the recent device selection updates and I'm not sure it is relevant any longer.
