### ISSUE TITLE
Half filled buffer issues with some audio interfaces on Mac OS

### ISSUE THREAD

**Issue by sinosoidal** [thestk/rtaudio#236]
I'm having a strange issue with only some cards on Mac OS. The sounds gets choppy and dirty. 

By generating a sine tone and inspecting the output we can clearly observe that half of the signal is empty as the following picture illustrates:

![Screenshot 2020-03-05 at 10 56 52](https://user-images.githubusercontent.com/1700060/76678947-21a2a200-65d4-11ea-836c-51e85e3aa784.png)

I can replicate this issue with a Behringer UMC204HD. I don't have any problems in Windows with the same card. Sample rate and buffer size settings doesn't seem to have any effect on this.

Other cards that have been reported as having this issue are Focusrite 18i20 and a MOTU that I can't remember the model right now but I will ask.

It is important to say that using the same device with the OS and/or with any DAW, works perfectly.

The DAC is being initialised with the following settings:

`Options -> RTAUDIO_SCHEDULE_REALTIME;
`Format -> RTAUDIO_FLOAT32

Has anyone ever stumbled on the same issue before? Any clues on how to sort this out?

Thanks!

**Comment by garyscavone** [comment]
Is it possibly related to the number of channels you have selected? If you only wanted to use 1 channel but the device somehow required filling 2 anyway, then perhaps those blank regions are for the 2nd channel (in a non-interleaved context). You might also see what happens when you switch between interleaved and non-interleaved (which will only matter for channels > 1).

**Comment by sinosoidal** [comment]
@garyscavone you are right. I was not paying attention to the number of channels requested and I was asking for the device channel count which was greater than 2. Thanks for your insight!
