### ISSUE TITLE
ASIO and (A)GPL licensing

### ISSUE THREAD

**Issue by alex-tee** [thestk/rtaudio#252]
Hi,

I am wondering what license the ASIO headers are under. They don't seem to have a license header, and this makes things even more confusing: https://manual.audacityteam.org/man/asio_audio_interface.html 

I have doubts whether I can distribute my (A)GPL application with rtaudio built with ASIO support, since ASIO doesn't seem to be under a compatible license.

Can someone please clarify the situation?

**Comment by radarsat1** [comment]
No one here is a lawyer, so the only advice I think that can be given is that if you are not sure, you should strip it from your distribution.  It's "at your own risk" to use it and distribute it.

**Comment by alex-tee** [comment]
thanks, of course, I am not looking for legal advice, and i do distribute builds without ASIO support. just wondering what the licensing on ASIO is or if it needs some kind of SDK agreement like the audacity link suggests. that kind of information should be included in the sources here IMO

**Comment by garyscavone** [comment]
I thought the main issue was distributing the ASIO files themselves, rather than an application that was built with ASIO support. I decided many years ago to include the ASIO files in the RtAudio distribution simply because I think it is too onerous to force developers to sign up with Steinberg just to get the files necessary for compiling.

**Comment by radarsat1** [comment]
In any case, for reference the exact license in question can be found in a PDF inside the zip file here: https://download.steinberg.net/sdk_downloads/asiosdk_2.3.3_2019-06-14.zip

https://www.steinberg.net/en/company/developers.html

Since it's a bit annoying to get the agreement this way, I extracted the text of the license:

[Steinberg ASIO Licensing Agreement.txt](https://github.com/thestk/rtaudio/files/4611992/Steinberg.ASIO.Licensing.Agreement.txt)

It doesn't seem to me that it's worth putting this text into the RtAudio distribution since it's something one is supposed to submit to Steinberg, but maybe it should be mentioned with a link in a README file.  For @alex-tee 's purposes I recommend he signs the agreement and sends it to the Steinberg address as per the [instructions](https://www.steinberg.net/en/company/developers.html), then I suppose he should be all clear to use it in his software.

**Comment by radarsat1** [comment]
To be clear, I agree that @alex-tee may have a point that we should indicate where users can get the ASIO SDK and its corresponding license agreement, even if we continue to include the headers for convenience.  Prepending some info into the headers wouldn't be a bad way.

**Comment by garyscavone** [comment]
I just added a file "asioinfo.txt" to the include directory with a pointer to the SDK and license agreement.
