### ISSUE TITLE
Does anyone fancy IAudioClient3 for WASAPI implementation?

### ISSUE THREAD

**Issue by ip4368** [thestk/rtaudio#259]
It looks like it is a big improvement in terms of latency starting from Windows 10.

> This makes it possible for an application to choose between the default buffer size (10ms) or a small buffer (<10ms) when opening a stream in shared mode.

https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/low-latency-audio#windows_audio_session_api_wasapi

It seems like it is something that fit the purpose of this project. Without requiring users to have an ASIO compatible hardware/installing ASIO4ALL and taking up exclusive control to the hardware could probably benefit many consumer-level users, who probably don't have much idea about pro audio.

I am happy to take a look into the implementation, but I don't usually have much free time, so if anyone see fit and willing to spend time onto it, feel free to take a look onto this.

**Comment by radarsat1** [comment]
Glad to hear of this, just the other day I was thinking it's kind of astounding that ASIO is still a necessary thing for Windows.  Unfortunately I don't have time for it either right now, but it's good to take note of.  Thanks.

**Comment by shangjiaxuan** [comment]
I added a bit of code to better negotiate the buffer size here #261. Difference in IAudioClient3 is mainly this buffer size negotiation. Having a large buffer will cause latency, but small buffer will cause audio glitch (normal shared mode callback calls when system mixer buffer is depleted, and using a buffer smaller than audio engine update size this will cause glitches. In this mode it calls when update is needed, and the default size is typically 10ms, with total software latency of 20ms). 

Currently RtAudio does not report this latency since it only calls GetLatency method and stores the value to be fetched. It seems not to mean the time it takes new samples to reach output, not considering the samples already in the buffer. (GetCurrentPadding can result in a better approximation, but will only be available in audio thread. A better approach is to update the value every update and leave a timestamp, the getlatency will calculate that with the time difference and samplerate. A more precise one can be implemented with QueryPerfCounter, and that will take into account the audio engine to speaker time. I implemented this in my fork of libsoundio)

**Comment by shangjiaxuan** [comment]
Using the smallest buffer size made the sound glitch on my device, it seems the default thread scheduler does not have that much precision. But adapting the buffer size to default value can reduce the queuing of extra buffers.

**Comment by shangjiaxuan** [comment]
It seems that the page in the link states:

> If the application uses WASAPI, then only the work items that were submitted to the Real-Time Work Queue API or MFCreateMFByteStreamOnStreamEx and were tagged as "Audio" or "ProAudio".

Thus the thread scheduler problem is to be expected. Will look into how to solve this.

**Comment by MarcusTomlinson** [comment]
This has been fixed in commit https://github.com/thestk/rtaudio/commit/f115d797dd65ddbc5d2fdd2a568c51e8a4d768ed
