### ISSUE TITLE
Device unique ID and new peripheral events

### ISSUE THREAD

**Issue by lp35** [thestk/rtaudio#276]
Hi there,

As for libsoundio, I think it could be very helpful to generate a unique device ID for each device. To my point of view, the ID of each device is not reliable as it can change at any time. Regarding the name of the device, is it unique for each device?

Also I would found very interesting to have a callback warning the application when a new device is available. That would prevent polling the API.

Anyway thanks for RtAudio, it's a great piece of code!

**Comment by garyscavone** [comment]
Done in the recent device selection updates.

**Comment by lp35** [comment]
Hi!

Sorry to reopen this, but this have been partially answered.
Indeed Device ID has been implemented. However, how can we have an "event like" system instead of polling system for detecting new devices?
Cheers!

**Comment by garyscavone** [comment]
All or nearly all underlying APIs do not provide callback mechanisms to alert us of new devices. A few provide functions to alert us if a device in use is disconnected and that has been incorporated where available to automatically close an open stream. Thus, at this time, it is not possible for RtAudio to provide an "event like" system to detect new devices without polling itself. Rather than add such functionality "under the hood," I'd prefer to leave it up to the user to poll as needed. For example, any time a UI element is triggered that lists devices, do the polling then.

**Comment by lp35** [comment]
Hey.

With ALSA, it is currently not possible to detect disconenction of devices.
