### ISSUE TITLE
How to use with CMake / different include paths on unix/windows?

### ISSUE THREAD

**Issue by autoantwort** [thestk/rtaudio#283]
I have installed the lib with vcpkg and used it with
```cmake
find_path(RtAudio_INCLUDE_DIR rtaudio/RtAudio.h)
find_library(RtAudio_LIBRARY rtaudio)
target_include_directories(lichtsteuerung PRIVATE ${RtAudio_INCLUDE_DIR})
target_link_libraries(lichtsteuerung ${RtAudio_LIBRARY})
```
But the include dir is `rtaudio/RTAudio.h` on Windows and `RtAudio.h` on Linux/Mac. I have also tried
```cmake
find_package(RtAudio CONFIG REQUIRED)
target_link_libraries(lichtsteuerung RtAudio::RtAudio)
```
but that didn't worked.  
[Here](https://github.com/microsoft/vcpkg/blob/master/ports/rtaudio/portfile.cmake) you can find the `vcpkg` portfile, if you would say that this is a problem of vcpkg and not rtaudio.

**Comment by dyfer** [comment]
I think this has to do with using pkgconfig with vcpkg (if not, then the rest of my answer is irrelevant).
In order to find VCPKG-installed RtAudio on Windows, I needed to add its pkgconfig file to an env variable like this:
`PKG_CONFIG_PATH=<VCPKG_INSTALLATION_ROOT>\installed\<triplet>\lib\pkgconfig`
Replace `VCPKG_INSTALLATION_ROOT` and `triplet` with values in your system.
Of course pkgconfig needs to be installed as well.

**Comment by radarsat1** [comment]
@dyfer @autoantwort can you confirm whether @albestro's patch in #310 fixes this problem?

**Comment by autoantwort** [comment]
Yeah it fixes the problem
