### ISSUE TITLE
rtaudio/include/dsound.h

### ISSUE THREAD

**Issue by jmansion** [thestk/rtaudio#45]
Is this file actually redistributable?

I was surprised to find it.  Windows SDk is free, isn't it appropriate to have that as a prerequisite?

**Comment by radarsat1** [comment]
I believe the problem is that things change a bit too fast and it's annoying to constantly keep up with every release of Windows when you're not a regular user.  I believe the intention of including it is simply to make "build and run" as simple as possible.  It's just a header after all.  That said, perhaps it would be better to "borrow" the [Wine version](http://source.winehq.org/git/wine.git/blob_plain/HEAD:/include/dsound.h) instead of the Windows version.
