### ISSUE TITLE
Split RtAudio.cpp into multiple files

### ISSUE THREAD

**Issue by joshdekock** [thestk/rtaudio#52]
As of writing this, RtAudio.cpp has 10230 lines, and as far as I can tell, it's the only source file which makes up RtAudio itself.
I'm sure this makes it very difficult to navigate (it definitely did for me), so wouldn't splitting it into multiple files, say, by class make it nicer to work with?

**Comment by garyscavone** [comment]
Personally, I prefer the single file.  It makes it much easier to search and edit similar code structures in the various classes.  And I prefer only needing to copy two files into a project when I want realtime audio support.

**Comment by joshdekock** [comment]
It was just a thought, I guess if people prefer having it all in one file, then it's not my place to try change that. Although, it might be a good idea to have some sort of index: an order of functions, so that, people who don't know what functions are in the file (and where they are), can quickly see an overview.

**Comment by pffang** [comment]
I think it's a good idea.
Splitting it into multiple files can make the codes more clear.

**Comment by cjcliffe** [comment]
I'm a fan of the single monolithic source -- mostly for simple for project inclusion.  Documentation at http://www.music.mcgill.ca/~gary/rtaudio/ was sufficient to implement without much need to read the source files but might be nice to have in the GitHub wiki for contributions and updates.

If it was ever broken up I'd still prefer to have a build target or script to compose it back into a single file like some javascript library release builders do.

**Comment by joshdekock** [comment]
> If it was ever broken up I'd still prefer to have a build target or script to compose it back into a single file like some javascript library release builders do.

This could be a viable compromise.

However, this brings me on to my next question, why isn't RtAudio distributed as a library? Surely this would remove the need for it to be in one source file, as people would link to the (static) library instead; they have to link to an object file anyways.

**Comment by DouglasHeriot** [comment]
RtAudio being one giant file is one reason I’ve hesitated to use it – it makes it harder for me to come at it and understand the structure. Before I start using a library, I need to be comfortable maintaining & bugfixing it if needed.

I like how SQLite solves this – you can develop it split into as many files as you want, and there’s a makefile that amalgamates it into a single file for easy inclusion. https://www.sqlite.org/amalgamation.html

**Comment by radarsat1** [comment]
> However, this brings me on to my next question, why isn't RtAudio distributed as a library?

The build does generate a library?

    $ make >/dev/null 2>&1 && find . -name \*.so
    ./.libs/librtaudio.so

**Comment by joshdekock** [comment]
Oh, sorry, maybe I wasn't clear enough, what I meant was: Why aren't people using a static library rather than including the actual file into their projects?

**Comment by radarsat1** [comment]
Probably because library management on Windows and Mac sucks.  Generating a .framework using open source tools sucks.  In the case of people using linux or homebrew/macports/whatever properly, they certainly should be using it as a library.  But you have to take the context into account: RtAudio is primarily a project aimed at making it as easy as possible for music students in music technology courses at university, who may be just learning how to program for the first time, to get audio output without much trouble.  The easiest thing is to tell them to simply copy the file into their project folder and be done with it.  Anything more complicated is distraction.  (For instance, teaching them what a "library" is, when they should be learning about audio synthesis algorithms.)

Anyways, that's the argument as I understand it.  I have often thought of suggesting to split up RtAudio into several files, but the benefits have never really outweighed the disadvantages *enough* for me to make an issue of it.  After all, if you have a decent text editor it's not a big deal to navigate a big cpp file, you just aren't used to it.  I've often expected a fork to show up one of these days that is focused around splitting things up ;)  And that would be fine.  But for RtAudio proper, I don't think it's necessarily the best course.
