### ISSUE TITLE
Can't build in Linux

### ISSUE THREAD

**Issue by pabloriera** [thestk/rtaudio#63]
Autoconf make no errors,

./autogen.sh --with-alsa --with-jack --with-pulse

but then make says,

RtAudio.cpp:1943:13: error: 'void jackSilentError(const char*)' defined but not used [-Werror=unused-function]
 static void jackSilentError( const char * ) {};
cc1plus: all warnings being treated as errors

I am doing something wrong apparently

Thanks in advance

**Comment by doe300** [comment]
The compiler warns about function is not being used.
This is not a problem at all, any good compiler removes any unused function from the final binary, any not-so-good compiler just leaves it in there, resulting in a few unused bytes in the program-file.

The problem is, that your compiler treats every warning as fatal error and therefore fails to compile.
The flag is probably set in [configure.ac](https://github.com/thestk/rtaudio/blob/master/configure.ac) in line 6 via `-Werror`.

The solution: don't treat every warning as error. Either remove the flag from the configuration-file or call the configuration with `-Wno-error` as argument (not tested).

**Comment by pabloriera** [comment]
Thanks, I was trying with a different flag to override the Werror, the flag -Wno-error did the trick.

**Comment by radarsat1** [comment]
Might be good to move `-Werror` to debug build only.
