### ISSUE TITLE
WASAPI: when using non-default sample rates, there are audio artifacts

### ISSUE THREAD

**Issue by paulmasri** [thestk/rtaudio#69]
_Affects RtAudio 4.1.2_

There appears to be very crude resampling of waveforms when the selected sample rate for the output stream doesn't match the default sample rate of the device. I have tested this on Windows 7, 8 & 10.

Here is an example waveform, captured via loopback, where the selected sample rate is 44100Hz and the default sample rate is 48000Hz. The red arrows indicate the "extra" samples that appear to have been added to achieve resampling and which result in significant audio artifacts.

![screen shot 2016-07-29 at 15 20 34](https://cloud.githubusercontent.com/assets/496858/17251305/0effed6c-55a0-11e6-8c02-f387e51e13ec.png)

Possibly related to #22 ?

**Comment by garyscavone** [comment]
Yes, this is a significant problem with the WASAPI implementation.  If I remember correctly, it resamples to nearest neighbour with truncation and at least could be improved with some linear interpolation. It would probably be better if the WASAPI implementation was in a development branch, not in the release branch, until this problem is fixed.

**Comment by paulmasri** [comment]
Thanks for all the awesome work you've done over the years @garyscavone. Please don't pull WASAPI... I'm relying on it for something that's going to production! :-o My workaround is to find out the default device's preferred sample rate and to use that (and do linear interpolation resampling within my app).

**Comment by MarcusTomlinson** [comment]
Damn, turns out I haven't properly fixed this issue yet. Turns out my interpolation logic was overrunning its buffers. Sorry about that!

**Comment by radarsat1** [comment]
Is it not possible to fix the buffer overrun without reverting the whole thing?  I'll merge your revert if necessary but are you sure you were completely on the wrong track?

**Comment by radarsat1** [comment]
Hm now that I'm looking at the code it seems to me that `WasapiBuffer` and `convertBufferWasapi` could be tested on their own without the need for WASAPI itself.  Can you suggest a way to test / detect the issue you are reporting?

**Comment by MarcusTomlinson** [comment]
It's not that I was on the wrong track really, I just felt that in the interim it'd be way better to leave users with a WASAPI API that actually worked while I investigate a fix. (The artefacts my "fix" introduced are far worse than the artefacts we had)

If you're interested in looking into it, the problem is with my retrieval of the **toSample**:
I'm indexing **toSample** as `[ frameInSample + channelCount + channel ]`
(Where `+ channelCount` is a frame jump to the sample following **frameInSample**).
Problem is, that overruns the end of the buffer.
What we need is to carry over the last frame of each buffer.

**Comment by MarcusTomlinson** [comment]
The other issue on my mind is conversions from high to a low sample rates. There ideally should be a low-pass filter inline before the interpolator to avoid aliasing of frequencies above Nyquist.

Sometimes I do wonder if we're trying to be too fancy with WASAPI tbh. WASAPI gives you just one supported sample rate to work with, so we're then jumping through hoops in order to provide users with more choice. I really like the convenience of it, but at what cost is the question.

**Comment by garyscavone** [comment]
Providing audio sample rate conversion functionality is definitely outside my originally intended scope for RtAudio. That said, it is sad that WASAPI is so limited in this regard. But if we do as with the other APIs, we would simply report the one supported sample rate and that would be the only option the user could use.

If you want to implement sample rate conversion properly, then I suggest the following link:

- https://ccrma.stanford.edu/~jos/resample/ <https://ccrma.stanford.edu/~jos/resample/>

But again, I consider that outside the intended scope of RtAudio, which is to provide a common API to access the audio functionality provided by various cross-platform audio APIs. If one or more of those APIs has limited functionality, it is not our job to try to fix that (it can be done further downstream if a client wishes).

**Comment by MarcusTomlinson** [comment]
How about we go for something in-between. We allow support for all sample rates equal to or above the device native sample rate. That way, we just need to fix the linear interpolator in convertBufferWasapi() and we avoid having to deal with the aliasing problem entirely.

**Comment by MarcusTomlinson** [comment]
Correction (It depends on the direction of the conversion):
For input streams it'd be sample rates equal to or above the device's native sample rate.
For output streams it'd be sample rates equal to or below the device's native sample rate.

**Comment by MarcusTomlinson** [comment]
I don't know when I'll be able to get to that ^ though (the interpolation fix), so I'd suggest merging what I have in https://github.com/thestk/rtaudio/pull/108 so far, then I (or someone willing) can create a new PR for the rest.

As I said, that'd at least give users something that works while interpolator is improved.

**Comment by garyscavone** [comment]
To do it correctly, you need a filter no matter whether you are upsampling or downsampling. Again, I think it best to avoid creating bugs and just stick to the single supported sample rate.

**Comment by MarcusTomlinson** [comment]
Hmm, yeah. Ok, I'm fine with that Gary. Could you please re-open this bug. I'll retract my PR, and try to create a new one ASAP. Thanks

**Comment by MarcusTomlinson** [comment]
Ok, was easier than I expected. Here's the new PR: https://github.com/thestk/rtaudio/pull/109

**Comment by radarsat1** [comment]
Yeah at the end of the day I agree, @garyscavone, better not provide sample rate conversion unless it's really done properly, and in that case it shouldn't be specific to an API, but shared for all of RtAudio.  In any case there is no point recreating libsamplerate.

**Comment by MarcusTomlinson** [comment]
PR #119 returns the ability to select a non-default sample rate, now with proper resampling support.
