### ISSUE TITLE
Can't build --with-oss on linux

### ISSUE THREAD

**Issue by luigino** [thestk/rtaudio#90]
See attached log.
And include/soundcard.h seems to be BSD-specific
[rtaudio_oss.txt](https://github.com/thestk/rtaudio/files/1057382/rtaudio_oss.txt)

**Comment by garyscavone** [comment]
Is there any convincing reason to use OSS these days? I have no way of testing it any longer. If someone with a Linux / OSS setup wants to try to fix this, please do. Otherwise, I think it should be deprecated.

**Comment by luigino** [comment]
I agree. I don't have a use case for OSS myself, it's just that it used to work until the last version I had packaged (4.0.x).

**Comment by radarsat1** [comment]
Are you sure you have an OSS v4 header installed?
I have /usr/include/sys/soundcard.h on my Ubuntu computer, but it doesn't compile.  I don't know where you see "include/soundcard.h" in the source.  I don't necessarily think it won't work, I think it's just a matter of having the right header version installed, but it doesn't seem to be possible on Ubuntu as far as I can tell.  I would have to test with Debian or Arch perhaps.

**Comment by radarsat1** [comment]
I just compile it in a Docker image of Debian Jessie with no problems.  Had to install the package `oss4-dev`

**Comment by radarsat1** [comment]
Dockerfile:

~~~
FROM debian:jessie

RUN apt-get update && apt-get install -y \
  build-essential git-core automake autoconf libtool oss4-dev

RUN git clone http://github.com/thestk/rtaudio && \
  cd rtaudio && autoreconf -i && ./configure --with-oss && make

~~~

**Comment by luigino** [comment]
SNDCTL_SYSINFO is indeed defined in the soundcard.h header supplied by debian.

The maintainer of the relevant package on openSUSE told me it's nonstandard and apparently a remnant of the commercial OSS v4 package.

I suppose I could borrow it and see what happens.

**Comment by garyscavone** [comment]
If I remember correctly, the last time I was able to get OSS to compile, some of the demo programs didn’t actually work. Did you try running any?

**Comment by radarsat1** [comment]
I couldn't in Docker, as it needs a kernel module installed.  Now I installed Debian Jessie to a Qemu VM and installed the oss4-dkms, oss4-base, and oss4-dev packages and compiled with `--with-oss`.  All test programs "worked" at 1 or 2 channels, 44100 and 48000 kHz, although record, and duplex modes did not seem to sound very good, and interleaved and non-interleaved modes sounded different, so there could be some bugs regarding buffer formats.  

Some of this could be down to emulation bugs, I used the Qemu virtual HDAudio driver for testing, with PulseAudio output configured.  Would have to install Debian to a partition to be sure, but I'm not willing to do that at the moment.

In any case, I would conclude that OSS is still basically supported, in the sense that it compiles with no errors and is able to read and write audio to the driver.  I see no reason to deprecate it for now.

@luigino  you still have not mentioned which operating system you are concerned with, or why you care about OSS support.  If you're testing on an operating system without OSS4, then it's a problem outside RtAudio.  If you're testing on an operating system where you expect it should work, please give more details or suggest some changes.  Otherwise I think we can close this.

**Comment by luigino** [comment]
@radarsat1 I'm updating the RtAudio package for openSUSE Leap and I've noticed this.
It's probably not a great problem if OSS is no longer supported, but I wanted to make sure it wasn't a trivial error on my part.

**Comment by radarsat1** [comment]
Right, no problem, I see now that it stemmed from wanting to compile or package pyrtaudio.  If you don't plan to support OSS on openSUSE, I suggest not using `--with-oss`, simple as that.
